### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by SethKitchen**
This works for me -- prob needs to also be done on Video -- but I only using image

### CODE REVIEW

**Comment by SethKitchen** [comment]
Reference Issue #8

**Comment by TesteurManiak** [comment]
Before accepting this merge can you please fix your `flutter analyze` issue.

**Comment by SethKitchen** [comment]
Try that @TesteurManiak

**Comment by TesteurManiak** [comment]
Everything seems good to me, thanks

**Pull request merged**
